"""Classification of every ssh_config keyword by whether claude-teleport may ignore it.

Grounded in: ssh_config(5) on OpenSSH 10.0p2, the keyword table in
internal/sshx/keywords.go, and what internal/sshx actually implements —
agent plus key-file auth, known_hosts verification against one file,
x/crypto/ssh defaults for cipher/KEX/MAC negotiation, and no ssh(1) binary.
"""

# (keyword, category, reason)
# Categories: honoured, refused, c, must, b, a, retired
ROWS = [
    # --- honoured: acted on today -------------------------------------------
    ("Host", "honoured", "Selects the block. Patterns matched per lookup."),
    ("Match", "honoured", "Selects the block; all/host guards per lookup, exec run against the allow list."),
    ("Include", "honoured", "Pulled in, parsed, and walked by the keyword check."),
    ("HostName", "honoured", "The address dialled."),
    ("User", "honoured", "The login name."),
    ("Port", "honoured", "The port dialled."),
    ("IdentityFile", "honoured", "Key files offered, in the order given."),
    ("ProxyJump", "honoured", "Jump chain, prepended to any --via hops."),
    ("ServerAliveInterval", "honoured", "Keepalive period; on by default here, unlike ssh."),
    ("ServerAliveCountMax", "honoured", "Keepalive misses tolerated before the link is dropped."),
    ("IgnoreUnknown", "honoured", "Which unknown keywords are tolerated rather than refused."),
    ("ProxyCommand", "refused", "Not ignored and not honoured: the run stops with an error naming --via."),

    # --- (c) never safe to ignore -------------------------------------------
    ("RevokedHostKeys", "c", "Ignoring accepts a host key the user explicitly revoked. The single worst entry on this page."),
    ("UserKnownHostsFile", "c", "Verification falls back to ~/.ssh/known_hosts, so a key the user deliberately kept out of their curated store is accepted. Read from -o today, not from the config."),
    ("HostKeyAlias", "c", "The key is checked under the real hostname instead of the alias, so the wrong known_hosts entry authorises the connection."),
    ("CASignatureAlgorithms", "c", "Widens which CA signatures are acceptable on host certificates beyond what the user allowed."),
    ("HostKeyAlgorithms", "c", "Widens which host key types are acceptable. A user who pinned ed25519 gets whatever the library negotiates."),
    ("Ciphers", "c", "A narrowed cipher list is discarded for library defaults; a cipher the user forbade can be negotiated."),
    ("MACs", "c", "Same: the user's MAC allow-list is replaced by library defaults."),
    ("KexAlgorithms", "c", "Same: the user's key-exchange allow-list is replaced by library defaults."),
    ("PubkeyAcceptedAlgorithms", "c", "We may sign with an algorithm the user disallowed, such as SHA-1 RSA."),
    ("RequiredRSASize", "c", "A host or user RSA key smaller than the stated floor is accepted."),
    ("RekeyLimit", "c", "A teleport moves far more data than a shell session, so a rekey limit set for that reason is exactly the one ignoring hurts."),
    ("IdentitiesOnly", "c", "Agent keys the user forbade are still offered, so the connection can authenticate as an unintended identity."),
    ("IdentityAgent", "c", "SSH_AUTH_SOCK is used instead of the named agent, which may hold a different key set the user deliberately isolated."),
    ("CanonicalizeHostname", "c", "Canonicalisation changes the name AND re-matches the config against it, so ignoring it can silently apply a different block: different user, key, port, jump."),

    # --- must ignore ---------------------------------------------------------
    ("RemoteCommand", "must", "Honouring it would run the user's command instead of the remote helper."),
    ("SessionType", "must", "“none” forbids remote command execution, which is the whole mechanism."),
    ("RequestTTY", "must", "Pty allocation is decided per step; the resume confirmation needs one, the streams must not have one."),
    ("LocalCommand", "must", "Honouring it would execute a command from a config file on connect."),
    ("PermitLocalCommand", "must", "The gate on LocalCommand; same reasoning."),
    ("StdinNull", "must", "Stdin is wired to the transfer streams, not to a terminal."),
    ("ForkAfterAuthentication", "must", "Backgrounding the client mid-run would orphan the job the runner is driving."),

    # --- (b) sometimes safe --------------------------------------------------
    ("ControlMaster", "b", "No connection sharing, so each dial authenticates again. Painful where every auth is a hardware-token tap."),
    ("ControlPath", "b", "Same. In some setups the control socket is the only route that is already authenticated."),
    ("ControlPersist", "b", "Same family."),
    ("StrictHostKeyChecking", "b", "Fails closed: our default already refuses unknown hosts, so ignoring a laxer config value only ever makes us stricter. Read from -o."),
    ("GlobalKnownHostsFile", "b", "/etc/ssh/ssh_known_hosts is never consulted, so a system-trusted host reads as unknown. Loud, not silent."),
    ("KnownHostsCommand", "b", "A host-key source consulted in addition to the files, so ignoring it only narrows what we trust."),
    ("UpdateHostKeys", "b", "Rotated host keys are never learned, so teleports break after a rotation that ssh would have absorbed."),
    ("VerifyHostKeyDNS", "b", "SSHFP records are never trusted here, which is stricter than asked, not laxer."),
    ("CheckHostIP", "b", "The extra address check is skipped. Laxer, but the keyword defaults to no in modern ssh anyway."),
    ("HashKnownHosts", "b", "Only bites under -o StrictHostKeyChecking=accept-new, where we append an unhashed line to a file the user asked to keep hashed."),
    ("CertificateFile", "b", "Certificates are never offered, so a certificate-only host refuses us loudly."),
    ("PKCS11Provider", "b", "Smartcard keys are unavailable; auth fails loudly rather than silently."),
    ("SecurityKeyProvider", "b", "FIDO authenticator keys are unavailable; same loud failure."),
    ("PasswordAuthentication", "b", "We never do passwords. A password-only host fails loudly."),
    ("KbdInteractiveAuthentication", "b", "Same, and this is where most MFA prompts live."),
    ("KbdInteractiveDevices", "b", "Only meaningful once keyboard-interactive is in play, which it never is."),
    ("PubkeyAuthentication", "b", "Set to no, ignoring it means we try the only method we have. Loud either way."),
    ("PreferredAuthentications", "b", "Method ordering is ours, which can spend attempts against a server that counts failures."),
    ("HostbasedAuthentication", "b", "Unsupported; a host requiring it refuses us loudly."),
    ("HostbasedAcceptedAlgorithms", "b", "Only meaningful with hostbased auth."),
    ("EnableSSHKeysign", "b", "Only meaningful with hostbased auth."),
    ("GSSAPIAuthentication", "b", "No Kerberos here; a site that mandates it cannot be reached at all."),
    ("GSSAPIKeyExchange", "b", "Same."),
    ("GSSAPIKexAlgorithms", "b", "Only meaningful with GSSAPI key exchange."),
    ("GSSAPIClientIdentity", "b", "Only meaningful with GSSAPI."),
    ("GSSAPIServerIdentity", "b", "Only meaningful with GSSAPI."),
    ("CanonicalDomains", "b", "Load-bearing only once CanonicalizeHostname is on, which is itself class (c)."),
    ("CanonicalizeMaxDots", "b", "Same."),
    ("CanonicalizePermittedCNAMEs", "b", "Same."),
    ("CanonicalizeFallbackLocal", "b", "Same."),
    ("AddressFamily", "b", "On a dual-stack host, the other family can be a different endpoint."),
    ("BindAddress", "b", "Source address selection, which some networks route or filter on."),
    ("BindInterface", "b", "Same."),
    ("ConnectTimeout", "b", "Our own 15s default applies, so a deliberately long timeout for a slow link is cut short."),
    ("ConnectionAttempts", "b", "We retry three times on our own schedule rather than theirs."),
    ("TCPKeepAlive", "b", "Superseded here by application-level keepalives, which we do honour."),
    ("ChannelTimeout", "b", "Idle channels are never reaped, which matters on a long-held transfer."),
    ("IPQoS", "b", "Packets go out unmarked, which a DSCP-shaped network may treat differently."),
    ("SendEnv", "b", "Variables the user expects on the far side never arrive, which can change what git or a hook does there."),
    ("SetEnv", "b", "Same."),
    ("ForwardAgent", "b", "Not forwarding is the safer default, but a destination Claude that needs to push over ssh will not be able to."),
    ("Tag", "b", "Only read by Match tagged, which we drop, so tagged blocks never apply. Consistent, but silently so."),

    # --- (a) always safe -----------------------------------------------------
    ("LocalForward", "a", "A teleport opens its own channels and carries no user forwardings."),
    ("RemoteForward", "a", "Same."),
    ("DynamicForward", "a", "Same."),
    ("ClearAllForwardings", "a", "There are no forwardings to clear."),
    ("ExitOnForwardFailure", "a", "There are no forwardings to fail."),
    ("GatewayPorts", "a", "Only meaningful with forwarded ports."),
    ("PermitRemoteOpen", "a", "Only meaningful with remote forwarding as a SOCKS proxy."),
    ("StreamLocalBindMask", "a", "Only meaningful for forwarded Unix sockets."),
    ("StreamLocalBindUnlink", "a", "Same."),
    ("Tunnel", "a", "No tun(4) device is ever requested."),
    ("TunnelDevice", "a", "Same."),
    ("ForwardX11", "a", "No X11 connection is ever made."),
    ("ForwardX11Trusted", "a", "Same."),
    ("ForwardX11Timeout", "a", "Same."),
    ("XAuthLocation", "a", "Only meaningful with X11 forwarding."),
    ("EscapeChar", "a", "There is no interactive terminal to escape from."),
    ("EnableEscapeCommandline", "a", "Same."),
    ("ObscureKeystrokeTiming", "a", "Nobody is typing; there are no keystroke timings to hide."),
    ("BatchMode", "a", "We never prompt, so the setting is already in force."),
    ("NumberOfPasswordPrompts", "a", "We never prompt for a password."),
    ("VisualHostKey", "a", "Display only; fingerprints are printed as text when a host is unknown."),
    ("FingerprintHash", "a", "Display only; our messages use SHA-256."),
    ("LogLevel", "a", "ssh(1) verbosity; this tool has its own job log."),
    ("LogVerbose", "a", "Same."),
    ("SyslogFacility", "a", "Same."),
    ("Compression", "a", "Throughput only, never correctness. Worth honouring one day: a teleport is mostly bulk transfer."),
    ("AddKeysToAgent", "a", "We never add keys to an agent, so nothing the user asked for is subverted."),
    ("GSSAPIDelegateCredentials", "a", "Not delegating credentials is strictly the safer outcome."),
    ("GSSAPIRenewalForcesRekey", "a", "Only meaningful with GSSAPI credentials in play."),
    ("GSSAPITrustDns", "a", "We never trust DNS to canonicalise a host name."),
    ("NoHostAuthenticationForLocalhost", "a", "Ignoring it means we verify localhost too, which is stricter."),
    ("ProxyUseFdpass", "a", "Only meaningful with ProxyCommand, which is refused outright."),
    ("VersionAddendum", "a", "Cosmetic text appended to the client banner."),
]

RETIRED = [
    ("Protocol", "SSH-1 selection; modern ssh parses and discards it."),
    ("Cipher", "SSH-1 cipher; superseded by Ciphers."),
    ("CompressionLevel", "SSH-1 only."),
    ("RSAAuthentication", "SSH-1 only."),
    ("RhostsRSAAuthentication", "SSH-1 only."),
    ("RhostsAuthentication", "Removed long ago."),
    ("DSAAuthentication", "Removed long ago."),
    ("FallBackToRsh", "Removed long ago."),
    ("UseRsh", "Removed long ago."),
    ("UsePrivilegedPort", "Removed with the setuid ssh client."),
    ("UseRoaming", "Removed after the 2016 roaming vulnerability."),
    ("SmartcardDevice", "Superseded by PKCS11Provider."),
    ("ChallengeResponseAuthentication", "Renamed to KbdInteractiveAuthentication."),
    ("KbdInteractiveDevices", None),  # placeholder, real entry is in ROWS
    ("PubkeyAcceptedKeyTypes", "Renamed to PubkeyAcceptedAlgorithms."),
    ("HostbasedKeyTypes", "Renamed to HostbasedAcceptedAlgorithms."),
]
RETIRED = [(k, v) for k, v in RETIRED if v is not None]
