"""Emit docs/ssh-config-keywords.md from classification_data.py.

Also the coverage check: every keyword ssh_config(5) defines, as recorded
in keywords.go, must be classified exactly once, and nothing may be
classified that ssh_config(5) does not define. Run from the repo root:

    uv run internal/sshx/classification_gen.py

It exits non-zero rather than writing a half-true page, so regenerating
after `keywords_gen.py` adds a keyword tells you at once that the new
keyword has no verdict yet.
"""
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from classification_data import ROWS, RETIRED  # noqa: E402

REPO = pathlib.Path(__file__).resolve().parents[2]
OUT = REPO / "docs" / "ssh-config-keywords.md"

# Coverage, against the generated keyword table rather than a hand list.
go = (REPO / "internal" / "sshx" / "keywords.go").read_text()
sec = go.split("var sshConfigKeywords = map[string]string{")[1].split("\n}")[0]
defined = re.findall(r'"[a-z0-9]+":\s*"([A-Za-z0-9]+)"', sec)

classified = [k for k, _, _ in ROWS] + [k for k, _ in RETIRED]
missing = sorted(set(defined) - set(classified))
extra = sorted(set(classified) - set(defined))
dupes = sorted({k for k in classified if classified.count(k) > 1})
if missing or extra or dupes:
    sys.exit(f"coverage: missing={missing} extra={extra} duplicated={dupes}")

BUCKETS = [
    ("c", "(c) Never safe to ignore",
     "Ignoring any of these can silently hand the user an outcome they "
     "explicitly forbade, and nothing in the run reveals that it happened. "
     "Every one either widens what cryptography or which host keys are "
     "acceptable, or changes which identity or which config block the "
     "connection uses."),
    ("must", "(d) Must be ignored",
     "Not a concession -- a requirement. Honouring these would break the "
     "teleport or turn the config file into a way to run commands. They are "
     "listed so the gap is a decision on the record rather than an oversight."),
    ("b", "(b) Sometimes safe to ignore",
     "Load-bearing in some configurations and inert in others, and the tool "
     "can usually tell which. Most fail loudly when they matter: the dial "
     "simply does not succeed. The few that fail quietly are marked, and "
     "they are the candidates for honouring next."),
    ("a", "(a) Always safe to ignore",
     "These shape an interactive ssh session or a feature a teleport never "
     "uses. Ignoring one cannot change where the connection goes, as whom, "
     "or how safely."),
]

# (b) entries that fail loudly rather than quietly when they matter.
LOUD = {
    "GlobalKnownHostsFile", "CertificateFile", "PKCS11Provider", "SecurityKeyProvider",
    "PasswordAuthentication", "KbdInteractiveAuthentication", "KbdInteractiveDevices",
    "PubkeyAuthentication", "HostbasedAuthentication", "HostbasedAcceptedAlgorithms",
    "EnableSSHKeysign", "GSSAPIAuthentication", "GSSAPIKeyExchange", "GSSAPIKexAlgorithms",
    "GSSAPIClientIdentity", "GSSAPIServerIdentity", "StrictHostKeyChecking",
    "VerifyHostKeyDNS", "KnownHostsCommand", "ConnectTimeout", "AddressFamily",
    "BindAddress", "BindInterface",
}


def rows_for(cat):
    return [(k, why) for k, c, why in ROWS if c == cat]


out = []
w = out.append

w("# ssh_config keywords: what a teleport may ignore")
w("")
w("<!-- Generated by internal/sshx/classification_gen.py. Do not edit by")
w("     hand; edit internal/sshx/classification_data.py and regenerate. -->")
w("")
w("`claude-teleport` speaks ssh through `golang.org/x/crypto/ssh` rather than")
w("running `ssh(1)` (spec section 4.2), so it reads `~/.ssh/config` itself and")
w("acts on a subset of it. This page is the verdict on **every** keyword")
w("`ssh_config(5)` defines, so that \"ignored\" is a recorded decision rather")
w("than an accident. `claude-teleport doctor <host>` prints which of these")
w("your config sets for a given host without the tool acting on them.")
w("")
w("The test applied throughout is not \"does this matter?\" but two sharper")
w("questions: **which way does ignoring fail** -- towards something more")
w("permissive than the user asked for, or more restrictive -- and **can the")
w("tool tell**. A setting whose neglect fails restrictively announces itself:")
w("the connection does not happen. One that fails permissively does not, and")
w("that is what separates (b) from (c).")
w("")
w("Grounded in `ssh_config(5)` on OpenSSH 10.0p2 and the keyword table in")
w(f"`internal/sshx/keywords.go` ({len(defined)} keywords), which is itself")
w("generated by asking the installed `ssh` which keywords it accepts.")
w("")

honoured = rows_for("honoured") + rows_for("refused")
w("## Honoured today")
w("")
w("Acted on rather than ignored: eleven honoured, plus `ProxyCommand`,")
w("which is refused outright so it can never be silently skipped.")
w("")
w("| Keyword | Effect |")
w("|---|---|")
for k, why in honoured:
    w(f"| `{k}` | {why} |")
w("")

for cat, title, blurb in BUCKETS:
    rows = rows_for(cat)
    w(f"## {title}")
    w("")
    w(blurb)
    w("")
    w(f"{len(rows)} keywords.")
    w("")
    if cat == "b":
        w("| Keyword | Fails | Why |")
        w("|---|---|---|")
        for k, why in rows:
            w(f"| `{k}` | {'loudly' if k in LOUD else '**quietly**'} | {why} |")
    else:
        w("| Keyword | Why |")
        w("|---|---|")
        for k, why in rows:
            w(f"| `{k}` | {why} |")
    w("")

w("## Retired by OpenSSH")
w("")
w("Parsed for compatibility and ignored by `ssh` itself, so ignoring them")
w("here matches what the user's own client does.")
w("")
w("| Keyword | Why |")
w("|---|---|")
for k, why in RETIRED:
    w(f"| `{k}` | {why} |")
w("")

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(out))
counts = {cat: len(rows_for(cat)) for cat, _, _ in BUCKETS}
print(f"wrote {OUT.relative_to(REPO)}: {len(defined)} keywords "
      f"({len(honoured)} honoured/refused, {counts}, {len(RETIRED)} retired)")
