#!/usr/bin/env python3
"""Regenerate keywords.go: the set of keywords ssh_config(5) defines.

Run from the repository root with a reasonably current OpenSSH installed:

    uv run internal/sshx/keywords_gen.py

Candidates are gathered from the ssh_config(5) man page, from `ssh -G`, and
from a hand list of keywords OpenSSH has carried at some point. Each candidate
is then put to ssh itself: a keyword is defined if ssh does not answer "Bad
configuration option" for it. That keeps the table honest against the ssh
actually installed rather than against anybody's memory of the manual.
"""
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

OUT = pathlib.Path("internal/sshx/keywords.go")

# Keywords OpenSSH has carried at some point, current or retired. A config
# carrying a retired one is old, not unreadable, so they stay in the table.
HISTORICAL = """
ChallengeResponseAuthentication Cipher CompressionLevel DSAAuthentication
FallBackToRsh GSSAPIClientIdentity GSSAPIServerIdentity HostbasedKeyTypes
KbdInteractiveDevices Protocol PubkeyAcceptedKeyTypes RhostsAuthentication
RhostsRSAAuthentication RSAAuthentication SmartcardDevice UseRoaming
UsePrivilegedPort UseRsh VerifyHostKeyDNS VersionAddendum
""".split()

# `ssh -G` answers in its own casing; prefer the manual's spelling for these.
CANON = {
    "canonicalizepermittedcnames": "CanonicalizePermittedCNAMEs",
    "casignaturealgorithms": "CASignatureAlgorithms",
    "gssapiauthentication": "GSSAPIAuthentication",
    "gssapidelegatecredentials": "GSSAPIDelegateCredentials",
    "gssapikexalgorithms": "GSSAPIKexAlgorithms",
    "gssapikeyexchange": "GSSAPIKeyExchange",
    "gssapirenewalforcesrekey": "GSSAPIRenewalForcesRekey",
    "gssapitrustdns": "GSSAPITrustDns",
    "hostname": "HostName",
    "ipqos": "IPQoS",
    "macs": "MACs",
    "pubkeyacceptedalgorithms": "PubkeyAcceptedAlgorithms",
}

# What this package actually reads out of a config. Kept beside the table so
# the two cannot drift; the generator refuses to run if one is not a keyword.
HONOURED = {
    "host": "block selector",
    "match": "block selector, with all/host/exec guards evaluated",
    "include": "pulled in and parsed",
    "hostname": "the address dialled",
    "user": "the login name",
    "port": "the port dialled",
    "identityfile": "key files offered, in order",
    "proxyjump": "jump chain, prepended to any --via hops",
    "proxycommand": "refused with an error naming --via",
    "serveraliveinterval": "keepalive period",
    "serveralivecountmax": "keepalive misses tolerated",
    "ignoreunknown": "which unknown keywords are tolerated",
}


def run(*a, **kw):
    return subprocess.run(a, capture_output=True, text=True, **kw)


def candidates():
    out = set(HISTORICAL)
    man = run("man", "5", "ssh_config").stdout
    man = subprocess.run(["col", "-b"], input=man, capture_output=True, text=True).stdout
    for line in man.splitlines():
        m = re.match(r"^ {7}([A-Za-z][A-Za-z0-9]+)", line)
        if m:
            out.add(m.group(1).rstrip(","))
    for line in run("ssh", "-G", "probe-host-does-not-exist").stdout.splitlines():
        if line.split():
            low = line.split()[0]
            out.add(CANON.get(low.lower(), low))
    return out


def defined(cands, workdir):
    """Keep the candidates ssh itself accepts as configuration options."""
    keep = []
    cfg = pathlib.Path(workdir) / "probe.conf"
    for kw in sorted(cands, key=str.lower):
        cfg.write_text(f"Host probe\n\t{kw} yes\n")
        r = run("ssh", "-F", str(cfg), "-G", "probe")
        if f"Bad configuration option: {kw.lower()}" not in r.stderr:
            keep.append(kw)
    return keep


def main():
    if not shutil.which("ssh"):
        sys.exit("ssh is not installed; this generator asks it what it accepts")
    version = run("ssh", "-V").stderr.strip() or run("ssh", "-V").stdout.strip()

    with tempfile.TemporaryDirectory() as workdir:
        keep = defined(candidates(), workdir)

    # One spelling per keyword, preferring a cased one over an all-lowercase.
    best = {}
    for k in keep:
        k = CANON.get(k.lower(), k)
        prev = best.get(k.lower())
        if prev is None or (prev.islower() and not k.islower()):
            best[k.lower()] = k
    keywords = sorted(best.values(), key=str.lower)

    missing = [h for h in HONOURED if h not in best]
    if missing:
        sys.exit(f"honoured keyword not in the defined set: {missing}")

    lines = [
        f"// Code generated by internal/sshx/keywords_gen.py against {version}.",
        "// Regenerate when OpenSSH gains keywords. The IgnoreUnknown escape",
        "// hatch exists because this table will go stale between regenerations.",
        "",
        "package sshx",
        "",
        "// sshConfigKeywords maps every keyword ssh_config(5) defines, lowercased,",
        "// to its canonical spelling. Keywords are case-insensitive, so the map is",
        "// keyed lowercase and the value is only ever used for display. Retired",
        "// keywords (Protocol, RSAAuthentication, ...) are kept: a config carrying",
        "// one is old, not unreadable.",
        "var sshConfigKeywords = map[string]string{",
    ]
    lines += [f'\t"{k.lower()}": "{k}",' for k in keywords]
    lines += [
        "}",
        "",
        "// honouredKeywords are the keywords this package acts on when it reads a",
        "// config (spec §4.2). Every other keyword in sshConfigKeywords is known to",
        "// be real and then ignored, which `doctor` reports for the host it is",
        "// given.",
        "var honouredKeywords = map[string]string{",
    ]
    lines += [f'\t"{k}": "{why}",' for k, why in sorted(HONOURED.items())]
    lines.append("}")

    OUT.write_text("\n".join(lines) + "\n")
    subprocess.run(["gofmt", "-w", str(OUT)], check=True)
    print(f"wrote {OUT}: {len(keywords)} keywords, {len(HONOURED)} honoured ({version})")


main()
