FROM golang:1.26 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /fakeapi-server ./test/fakeapi-server
FROM debian:trixie-slim
COPY --from=build /fakeapi-server /fakeapi-server
EXPOSE 8080
